# Generated by Django 4.0.1 on 2022-01-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_rename_itemname_weapon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='weapon',
            name='damagetype',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('basic', (('bludg', 'Bludgeoning'), ('pierce', 'Piercing'), ('slash', 'Slashing'))), ('elemental', (('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('light', 'Lightning'), ('thund', 'Thunder'))), ('acid', 'Acid'), ('necro', 'Necrotic'), ('poison', 'Poison'), ('psych', 'Psychic'), ('radiant', 'Radiant')], max_length=50),
        ),
        migrations.AddField(
            model_name='weapon',
            name='plusorminus',
            field=models.CharField(blank=True, choices=[('PLUS', '+'), ('MINUS', '-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='amountofdice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dicetype',
            field=models.CharField(blank=True, choices=[('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20'), ('D100', 'd100')], max_length=4),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='modifier',
            field=models.IntegerField(blank=True),
        ),
    ]
