# Generated by Django 4.0.1 on 2022-01-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_rename_user_weapon_created_by_weapon_damagetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='damagetype',
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage',
            field=models.CharField(choices=[('none', 'None'), ('basic', (('bludg', 'Bludgeoning'), ('pierce', 'Piercing'), ('slash', 'Slashing'))), ('elemental', (('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('light', 'Lightning'), ('thund', 'Thunder'))), ('acid', 'Acid'), ('necro', 'Necrotic'), ('poison', 'Poison'), ('psych', 'Psychic'), ('radiant', 'Radiant')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
